### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.10.2', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

In [3]:
import os
# 1. Tắt chế độ chờ để tránh lãng phí RAM
os.environ["UNSLOTH_VLLM_STANDBY"] = "0"

In [4]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 4096 # Can increase for longer reasoning traces
model_name = "Qwen3-4B-Base"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = f"unsloth/{model_name}",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    gpu_memory_utilization = 0.7, # Reduce if out of memory
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 02-26 04:24:50 [__init__.py:244] Automatically detected platform cuda.
ERROR 02-26 04:24:53 [fa_utils.py:57] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 02-26 04:25:05 [vllm_utils.py:723] Unsloth: Patching vLLM v1 graph capture
INFO 02-26 04:25:05 [vllm_utils.py:752] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2026.2.1: Fast Qwen3 patching. Transformers: 4.56.2. vLLM: 0.9.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/qwen3-4b-base-unsloth-bnb-4bit with actual GPU utilization = 69.32%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 4096. Num Sequences = 32.
Unsloth: vLLM's KV Cache can use up to 7.08 GB. Also swap space = 0 GB.
Unsloth: `cudagraph_mode` is not in `from vllm.config import CompilationConfig`
Unsloth: Disabling `disable_cascade_attn` in vLLM to allow for better on policy RL!
INFO 02-26 04:25:39 [config.py:841] This model supports multiple tasks: {'generate', 'classify', 'reward', 'embed'}. Defaulting to 'generate'.

`torch_dtype` is deprecated! Use `dtype` instead!

WARNING 02-26 04:25:39 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 02-26 04:25:39 [config.py:1472] Using max model len 4096
WARNING 02-26 04:25:39 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
INFO 02-26 04:25:41 [config.py:2285] Chunked prefill is enabled with max_num_batched_tokens=4096.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.0.mlp', 'model.layers.4.mlp', 'model.layers.3.self_attn', 'model.layers.0.self_attn', 'model.layers.6.mlp', 'model.layers.1.self_attn', 'model.layers.1.mlp', 'model.layers.2.mlp'], 'llm_int8_threshold': 6.0}
INFO 02-26 04:25:41 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='unsloth/qwen3-4b-base-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/qwen3-4b-base-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.BITSANDBYTES, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/qwen3-4b-base-unsloth-bnb-4bit, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"max_capture_size":32,"local_cache_dir":null}, use_cached_outputs=False,

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/166 [00:00<?, ?B/s]

INFO 02-26 04:25:48 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 02-26 04:25:48 [cuda.py:360] Using XFormers backend.
INFO 02-26 04:25:49 [parallel_state.py:1076] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 02-26 04:25:49 [model_runner.py:1171] Starting to load model unsloth/qwen3-4b-base-unsloth-bnb-4bit...
INFO 02-26 04:25:50 [bitsandbytes_loader.py:499] Loading weights with BitsAndBytes quantization. May take a while ...
INFO 02-26 04:25:51 [weight_utils.py:292] Using model weights format ['*.safetensors']

model.safetensors:   0%|          | 0.00/3.32G [00:00<?, ?B/s]

INFO 02-26 04:26:24 [weight_utils.py:308] Time spent downloading weights for unsloth/qwen3-4b-base-unsloth-bnb-4bit: 32.712649 seconds
INFO 02-26 04:26:24 [weight_utils.py:345] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 02-26 04:26:28 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 02-26 04:26:29 [model_runner.py:1203] Model loading took 3.3601 GiB and 38.592850 seconds
INFO 02-26 04:26:40 [worker.py:294] Memory profiling takes 10.62 seconds
INFO 02-26 04:26:40 [worker.py:294] the current vLLM instance can use total_gpu_memory (14.56GiB) x gpu_memory_utilization (0.69) = 10.10GiB
INFO 02-26 04:26:40 [worker.py:294] model weights take 3.36GiB; non_torch_memory takes 0.03GiB; PyTorch activation peak memory takes 0.37GiB; the rest of the memory reserved for KV Cache is 6.33GiB.
INFO 02-26 04:26:41 [executor_base.py:113] # cuda blocks: 2881, # CPU blocks: 0
INFO 02-26 04:26:41 [executor_base.py:118] Maximum concurrency for 4096 tokens per request: 11.25x
INFO 02-26 04:26:41 [vllm_utils.py:757] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 02-26 04:26:41 [model_runner.py:1513] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/7 [00:00<?, ?it/s]

INFO 02-26 04:26:55 [model_runner.py:1671] Graph capturing finished in 14 secs, took 0.18 GiB
INFO 02-26 04:26:55 [vllm_utils.py:764] Unsloth: Patched vLLM v0 graph capture finished in 14 secs.
INFO 02-26 04:26:56 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 26.68 seconds
Unsloth: Just some info: will skip parsing ['norm', 'post_feedforward_layernorm', 'k_norm', 'post_attention_layernorm', 'ffn_norm', 'layer_norm2', 'norm2', 'q_norm', 'input_layernorm', 'layer_norm1', 'post_layernorm', 'attention_norm', 'norm1', 'pre_feedforward_layernorm']

Some weights of Qwen3ForCausalLM were not initialized from the model checkpoint at unsloth/qwen3-4b-base-unsloth-bnb-4bit and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['norm', 'post_feedforward_layernorm', 'k_norm', 'post_attention_layernorm', 'ffn_norm', 'layer_norm2', 'norm2', 'q_norm', 'cross_attn_post_attention_layernorm', 'input_layernorm', 'layer_norm1', 'post_layernorm', 'attention_norm', 'cross_attn_input_layernorm', 'norm1', 'pre_feedforward_layernorm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

In [5]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
# Select only numbers
dataset = dataset.iloc[np.where(is_number)[0]]

dataset

README.md:   0%|          | 0.00/603 [00:00<?, ?B/s]

data/cot-00000-of-00001.parquet:   0%|          | 0.00/106M [00:00<?, ?B/s]

Generating cot split:   0%|          | 0/19252 [00:00<?, ? examples/s]

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

In [6]:
dataset['generated_solution'][0]

"<think>\nOkay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\n</think>To solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]"

In [7]:
sample_dataset = dataset.sample(n=500, random_state=42)
sample_dataset

,expected_answer,problem,generated_solution
11495,25,"Suppose that three prime numbers $p, q,$ and $...","<think>\nOkay, let's see. I need to solve this..."
14443,15,Let \( x \) and \( y \) be positive integers s...,"<think>\nOkay, let's see. I need to solve this..."
12123,375,What is the remainder when the product \(1 \ti...,"<think>\nOkay, so I need to find the remainder..."
2631,7,A set of consecutive positive integers beginni...,"<think>\nOkay, let's see. The problem is about..."
12441,8,A set \( S \) of points in the \( xy \)-plane ...,"<think>\nOkay, let me try to solve this proble..."
...,...,...,...
7735,1,Given the conditions \(0 < a \le b \le c\) and...,"<think>\nOkay, so I need to find the minimum v..."
2178,864,Find the number of permutations of the letters...,"<think>\nOkay, so I need to find the number of..."
19152,2017,Find all $x \in \mathbb{R}$ such that $$ x - \...,"<think>\nOkay, so I need to solve the equation..."
120,3,"Given non-negative numbers \(x, y, z\) such th...","<think>\nOkay, so I need to find the minimum v..."
16581,155,What is the smallest composite value of \( n^2...,"<think>\nOkay, let's see. The problem is askin..."

In [8]:
from vllm import SamplingParams
text = "What is the sqrt of 101?"

sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

' - HomeworkLib\nQuestion\nWhat is the sqrt of 101?\nWhat is the sqrt of 101?\nalgebra Radicals-And-Geometry-Arc-Length-Arc-Sectiom Area-Pi-Phi-Trigonometry\n1 Answer\n0 0\n2\n2 2 x20101(x+1)y−(x−1)y+xn−xn−1 x n −xn n = (0,x1 +x−1 +xn +xn 1 +1)−xn n\n0 x0+x1+n+x−1+n = ( ( (0,x1 + x−1 + xn = ( n x ⋅ 0 + xn + n + 1)\n00×x1+n = x1+(−1)+n+n 0 ×x1 + n = x1 + (−1) + n + n\n(2n+0+0)×(0)+ (0+n)+[ (1+n)+(−1)+n]×((x)0+(0+n)+(n+1))×(xn+(n+n+n) × ((x)0 −(1+n)+(n+0+n+1))+( (1+n)+ (−1)+(0+n)×(−1)+xn+(−1+n)+xn+(n+0+n))\n0+0+1+[ (0+0)−(0+0+0)]× (0)+0+0+0+[1+ (0+n)+ (n+0+n+0)]×0+0−0+0+[0+ (−1+n) +(n+0+n)+(1+n)+(−1)+(0+n)+0−0+(n+0+n+[0+(1+n)+(−1)+(0+n)+1+n)+−1+(1+n)+ n+0+n+[0+(1+n)+(−1)+(0+n)+1+n)+1+n+[0+(−1+n)+(n+0+n)+(1+n)+(−1)+(0+n)+0−0+(n+0+n) +0)+1+n+[0+(−1+n)+(n+0+n)+(1+n)+(−1)+(0+n)+0−0+(n+0+n)+0−1+(1+n)+n+0+n+[0+(1+n)+(−1)+(0+n)+1+n)\n1+[ ( ( (0+0))×(0)+(0+0)+ (0))+1]×(0)+0+[ (1+(0+n)+ (n+1+n)+1+[0+ (−1+n)+ (n+0+n)+ (1+n)+(−1)+(0+n)+0−0+(n+1+n+1))+0+ [(1+ (0+n)+ (n+0+n+0)+(−1+n)+ (n+0+n)+(1+n)+(−1)+ (0+n))+(0+ (−1+n)+ (n+0+n) +(1+n)+(−\n+1)+(1))]×(0)+ [0+(−1+n)+ (n+0+n)+ (1+n)+(−1)]+[0+ (−1+n)+(n+0+n)+ (1+n)+ (−1)]'

In [9]:
def apply_qwen_math_template(question: str):
    return (
        "<|im_start|>system\nPlease reason step by step, and put your final answer within \\boxed{}.<|im_end|>\n<|im_start|>user\n"
        + question
        + "<|im_end|>\n<|im_start|>assistant\n"
    )


def apply_r1_template(question: str):
    return (
        "A conversation between User and Assistant. The User asks a question, and the Assistant solves it. The Assistant first thinks about the reasoning process in the mind and then provides the User with the answer. "
        "The reasoning process is enclosed within <think> </think> and answer is enclosed within <answer> </answer> tags, respectively, i.e., <think> reasoning process here </think> <answer> answer here </answer>.\nUser: "
        + question
        + "\nAssistant: <think>"
    )

In [ ]:
from vllm import SamplingParams
from tqdm import tqdm
import pandas as pd

def inference_500_questions(template_type, model,n_samples, dataset, temperature, batch_size=50):
    FastLanguageModel.for_inference(model)
    all_problems = dataset["problem"].tolist()

    if template_type == "qwen_math_template":
        prompts = [apply_qwen_math_template(p) for p in all_problems]
    elif template_type == "r1_template":
        prompts = [apply_r1_template(p) for p in all_problems]
    else:
        prompts = all_problems

    sampling_params = SamplingParams(
        temperature=temperature,
        top_p=0.95,
        max_tokens=2048,
        n=n_samples,  
    )


    generated_results = []

    for i in tqdm(range(0, len(prompts), batch_size), desc="Inference"):
        batch_prompts = prompts[i : i + batch_size]

        outputs = model.fast_generate(
            batch_prompts,
            sampling_params=sampling_params
        )

        for output in outputs:
            answers = [o.text for o in output.outputs]
            generated_results.append(answers)

    data_rows = []
    for q, answers in zip(dataset["problem"], generated_results):
        row = {"Question": q}
        for i in range(8):
            row[f"Answer_{i+1}"] = answers[i]
        data_rows.append(row)

    df = pd.DataFrame(data_rows)

    filename = f"{model_name}_{temperature}_pass8.csv"
    df.to_csv(filename, index=False, encoding='utf-8-sig')

    print(f"Save as {filename}")
    return df

In [ ]:
df2 =inference_500_questions("no_template", model, sample_dataset, 1,100)